project:
  type: website
  output-dir: docs

website:
  title: "Shishir's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - Homework1/hw1_questions.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



